	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_8725A2C::
	.incbin "sound/direct_sound_samples/8725A2C.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_872762C::
	.incbin "sound/direct_sound_samples/872762C.bin"

	.align 2
DirectSoundWaveData_872921C::
	.incbin "sound/direct_sound_samples/872921C.bin"

	.align 2
DirectSoundWaveData_872A5D0::
	.incbin "sound/direct_sound_samples/872A5D0.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_872EEA8::
	.incbin "sound/direct_sound_samples/872EEA8.bin"

	.align 2
DirectSoundWaveData_87301B0::
	.incbin "sound/direct_sound_samples/87301B0.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_8734298::
	.incbin "sound/direct_sound_samples/8734298.bin"

	.align 2
DirectSoundWaveData_87364A8::
	.incbin "sound/direct_sound_samples/87364A8.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_87385E4::
	.incbin "sound/direct_sound_samples/87385E4.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_873ECD8::
	.incbin "sound/direct_sound_samples/873ECD8.bin"

	.align 2
DirectSoundWaveData_8740818::
	.incbin "sound/direct_sound_samples/8740818.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_87424B0::
	.incbin "sound/direct_sound_samples/87424B0.bin"

	.align 2
DirectSoundWaveData_87430C0::
	.incbin "sound/direct_sound_samples/87430C0.bin"

	.align 2
DirectSoundWaveData_8743C50::
	.incbin "sound/direct_sound_samples/8743C50.bin"

	.align 2
DirectSoundWaveData_87446EC::
	.incbin "sound/direct_sound_samples/87446EC.bin"

	.align 2
DirectSoundWaveData_8745034::
	.incbin "sound/direct_sound_samples/8745034.bin"

	.align 2
DirectSoundWaveData_8745A7C::
	.incbin "sound/direct_sound_samples/8745A7C.bin"

	.align 2
Cry_Bulbasaur::
Cry_Ivysaur::
Cry_Venusaur::
Cry_Charmander::
Cry_Charmeleon::
Cry_Charizard::
Cry_Squirtle::
Cry_Wartortle::
Cry_Blastoise::
Cry_Caterpie::
Cry_Metapod::
Cry_Butterfree::
Cry_Weedle::
Cry_Kakuna::
Cry_Beedrill::
Cry_Pidgey::
Cry_Pidgeotto::
Cry_Pidgeot::
Cry_Rattata::
Cry_Raticate::
Cry_Spearow::
Cry_Fearow::
Cry_Ekans::
Cry_Arbok::
Cry_Pikachu::
Cry_Raichu::
Cry_Sandshrew::
Cry_Sandslash::
Cry_NidoranF::
Cry_Nidorina::
Cry_Nidoqueen::
Cry_NidoranM::
Cry_Nidorino::
Cry_Nidoking::
Cry_Clefairy::
Cry_Clefable::
Cry_Vulpix::
Cry_Ninetales::
Cry_Jigglypuff::
Cry_Wigglytuff::
Cry_Zubat::
Cry_Golbat::
Cry_Oddish::
Cry_Gloom::
Cry_Vileplume::
Cry_Paras::
Cry_Parasect::
Cry_Venonat::
Cry_Venomoth::
Cry_Diglett::
Cry_Dugtrio::
Cry_Meowth::
Cry_Persian::
Cry_Psyduck::
Cry_Golduck::
Cry_Mankey::
Cry_Primeape::
Cry_Growlithe::
Cry_Arcanine::
Cry_Poliwag::
Cry_Poliwhirl::
Cry_Poliwrath::
Cry_Abra::
Cry_Kadabra::
Cry_Alakazam::
Cry_Machop::
Cry_Machoke::
Cry_Machamp::
Cry_Bellsprout::
Cry_Weepinbell::
Cry_Victreebel::
Cry_Tentacool::
Cry_Tentacruel::
Cry_Geodude::
Cry_Graveler::
Cry_Golem::
Cry_Ponyta::
Cry_Rapidash::
Cry_Slowpoke::
Cry_Slowbro::
Cry_Magnemite::
Cry_Magneton::
Cry_Farfetchd::
Cry_Doduo::
Cry_Dodrio::
Cry_Seel::
Cry_Dewgong::
Cry_Grimer::
Cry_Muk::
Cry_Shellder::
Cry_Cloyster::
Cry_Gastly::
Cry_Haunter::
Cry_Gengar::
Cry_Onix::
Cry_Drowzee::
Cry_Hypno::
Cry_Krabby::
Cry_Kingler::
Cry_Voltorb::
Cry_Electrode::
Cry_Exeggcute::
Cry_Exeggutor::
Cry_Cubone::
Cry_Marowak::
Cry_Hitmonlee::
Cry_Hitmonchan::
Cry_Lickitung::
Cry_Koffing::
Cry_Weezing::
Cry_Rhyhorn::
Cry_Rhydon::
Cry_Chansey::
Cry_Tangela::
Cry_Kangaskhan::
Cry_Horsea::
Cry_Seadra::
Cry_Goldeen::
Cry_Seaking::
Cry_Staryu::
Cry_Starmie::
Cry_MrMime::
Cry_Scyther::
Cry_Jynx::
Cry_Electabuzz::
Cry_Magmar::
Cry_Pinsir::
Cry_Tauros::
Cry_Magikarp::
Cry_Gyarados::
Cry_Lapras::
Cry_Ditto::
Cry_Eevee::
Cry_Vaporeon::
Cry_Jolteon::
Cry_Flareon::
Cry_Porygon::
Cry_Omanyte::
Cry_Omastar::
Cry_Kabuto::
Cry_Kabutops::
Cry_Aerodactyl::
Cry_Snorlax::
Cry_Articuno::
Cry_Zapdos::
Cry_Moltres::
Cry_Dratini::
Cry_Dragonair::
Cry_Dragonite::
	.incbin "sound/direct_sound_samples/cries/amogus.bin"

	.align 2
Cry_Mewtwo::
	.incbin "sound/direct_sound_samples/cries/amongus.bin"

	.align 2
Cry_Mew::
	.incbin "sound/direct_sound_samples/cries/frigorob.bin"

	.align 2
Cry_Chikorita::
Cry_Bayleef::
Cry_Meganium::
Cry_Cyndaquil::
Cry_Quilava::
Cry_Typhlosion::
Cry_Totodile::
Cry_Croconaw::
Cry_Feraligatr::
Cry_Sentret::
Cry_Furret::
Cry_Hoothoot::
Cry_Noctowl::
Cry_Ledyba::
Cry_Ledian::
Cry_Spinarak::
Cry_Ariados::
Cry_Crobat::
Cry_Chinchou::
Cry_Lanturn::
Cry_Pichu::
Cry_Cleffa::
Cry_Igglybuff::
Cry_Togepi::
Cry_Togetic::
Cry_Natu::
Cry_Xatu::
Cry_Mareep::
Cry_Flaaffy::
Cry_Ampharos::
Cry_Bellossom::
Cry_Marill::
Cry_Azumarill::
Cry_Sudowoodo::
Cry_Politoed::
Cry_Hoppip::
Cry_Skiploom::
Cry_Jumpluff::
Cry_Aipom::
Cry_Sunkern::
Cry_Sunflora::
Cry_Yanma::
Cry_Wooper::
Cry_Quagsire::
Cry_Espeon::
Cry_Umbreon::
Cry_Murkrow::
Cry_Slowking::
Cry_Misdreavus::
	.incbin "sound/direct_sound_samples/cries/amogus.bin"

	.align 2
Cry_Unown::
	.incbin "sound/direct_sound_samples/cries/amogusmathias.bin"

	.align 2
Cry_Wobbuffet::
Cry_Girafarig::
Cry_Pineco::
Cry_Forretress::
Cry_Dunsparce::
Cry_Gligar::
Cry_Steelix::
Cry_Snubbull::
Cry_Granbull::
Cry_Qwilfish::
Cry_Scizor::
Cry_Shuckle::
Cry_Heracross::
Cry_Sneasel::
Cry_Teddiursa::
Cry_Ursaring::
Cry_Slugma::
Cry_Magcargo::
Cry_Swinub::
Cry_Piloswine::
Cry_Corsola::
Cry_Remoraid::
Cry_Octillery::
Cry_Delibird::
Cry_Mantine::
Cry_Skarmory::
Cry_Houndour::
Cry_Houndoom::
Cry_Kingdra::
Cry_Phanpy::
Cry_Donphan::
Cry_Porygon2::
Cry_Stantler::
Cry_Smeargle::
Cry_Tyrogue::
Cry_Hitmontop::
Cry_Smoochum::
Cry_Elekid::
Cry_Magby::
Cry_Miltank::
Cry_Blissey::
	.incbin "sound/direct_sound_samples/cries/amogus.bin"

	.align 2
Cry_Raikou::
Cry_Entei::
Cry_Suicune::
	.incbin "sound/direct_sound_samples/cries/amongus.bin"

	.align 2
Cry_Larvitar::
Cry_Pupitar::
Cry_Tyranitar::
	.incbin "sound/direct_sound_samples/cries/amogus.bin"

	.align 2
Cry_Lugia::
Cry_HoOh::
Cry_Celebi::
	.incbin "sound/direct_sound_samples/cries/amongus.bin"

	.align 2
Cry_Kecleon::
Cry_Roselia::
Cry_Torkoal::
Cry_Electrike::
Cry_Manectric::
Cry_Duskull::
	.incbin "sound/direct_sound_samples/cries/amogus.bin"

	.align 2
Cry_Latias::
	.incbin "sound/direct_sound_samples/cries/amongus.bin"

	.align 2
Cry_Wynaut::
Cry_Seviper::
Cry_Sharpedo::
Cry_Zangoose::
Cry_Azurill::
Cry_Swablu::
Cry_Altaria::
Cry_Unused265::
Cry_Taillow::
Cry_Swellow::
Cry_Unused268::
Cry_Spinda::
	.incbin "sound/direct_sound_samples/cries/amogus.bin"

	.align 2
Cry_Torchic::
Cry_Combusken::
Cry_Blaziken::
Cry_Treecko::
Cry_Grovyle::
Cry_Sceptile::
Cry_Mudkip::
Cry_Marshtomp::
Cry_Swampert::
	.incbin "sound/direct_sound_samples/cries/amogos.bin"

	.align 2
Cry_Pelipper::
Cry_Wingull::
Cry_Banette::
Cry_Shuppet::
Cry_Lotad::
Cry_Lombre::
Cry_Ludicolo::
Cry_Seedot::
Cry_Nuzleaf::
Cry_Shiftry::
Cry_Carvanha::
Cry_Wurmple::
Cry_Silcoon::
Cry_Beautifly::
Cry_Cascoon::
Cry_Dustox::
Cry_Ralts::
Cry_Kirlia::
Cry_Gardevoir::
Cry_Slakoth::
Cry_Vigoroth::
Cry_Slaking::
Cry_Nincada::
Cry_Ninjask::
	.incbin "sound/direct_sound_samples/cries/amogus.bin"

	.align 2
Cry_Shedinja::
	.incbin "sound/direct_sound_samples/cries/amogusmathias.bin"

	.align 2
Cry_Makuhita::
Cry_Hariyama::
Cry_Nosepass::
Cry_Glalie::
Cry_Plusle::
Cry_Minun::
Cry_Surskit::
Cry_Masquerain::
Cry_Skitty::
Cry_Delcatty::
Cry_Gulpin::
Cry_Swalot::
Cry_Numel::
Cry_Camerupt::
Cry_Barboach::
Cry_Whiscash::
Cry_Corphish::
Cry_Crawdaunt::
Cry_Spoink::
Cry_Grumpig::
Cry_Trapinch::
Cry_Vibrava::
Cry_Flygon::
Cry_Cacnea::
Cry_Cacturne::
Cry_Baltoy::
Cry_Claydol::
Cry_Lunatone::
Cry_Solrock::
Cry_Feebas::
Cry_Milotic::
Cry_Absol::
Cry_Meditite::
Cry_Medicham::
Cry_Spheal::
Cry_Sealeo::
Cry_Walrein::
Cry_Clamperl::
Cry_Huntail::
Cry_Gorebyss::
Cry_Lileep::
Cry_Cradily::
Cry_Anorith::
Cry_Armaldo::
Cry_Beldum::
Cry_Metang::
Cry_Metagross::
Cry_Bagon::
Cry_Shelgon::
	.incbin "sound/direct_sound_samples/cries/amogus.bin"

	.align 2
Cry_Regirock::
Cry_Regice::
Cry_Registeel::
	.incbin "sound/direct_sound_samples/cries/falgus.bin"

	.align 2
Cry_Castform::
	.incbin "sound/direct_sound_samples/cries/amogusdoom.bin"

	.align 2
Cry_Volbeat::
Cry_Illumise::
Cry_Poochyena::
Cry_Mightyena::
Cry_Dusclops::
Cry_Sableye::
Cry_Mawile::
Cry_Aron::
Cry_Lairon::
Cry_Aggron::
	.incbin "sound/direct_sound_samples/cries/amogus.bin"

	.align 2
Cry_Relicanth::
	.incbin "sound/direct_sound_samples/cries/amogusatma.bin"

	.align 2
Cry_Luvdisc::
	.incbin "sound/direct_sound_samples/cries/amogus.bin"

	.align 2
Cry_Groudon::
Cry_Kyogre::
Cry_Rayquaza::
	.incbin "sound/direct_sound_samples/cries/amongus.bin"

	.align 2
Cry_Salamence::
Cry_Breloom::
Cry_Shroomish::
Cry_Linoone::
Cry_Tropius::
Cry_Wailmer::
Cry_Zigzagoon::
Cry_Exploud::
Cry_Loudred::
	.incbin "sound/direct_sound_samples/cries/amogus.bin"

	.align 2
Cry_Wailord::
	.incbin "sound/direct_sound_samples/cries/amogusatma.bin"

	.align 2
Cry_Whismur::
Cry_Snorunt::
	.incbin "sound/direct_sound_samples/cries/amogus.bin"

	.align 2
Cry_Latios::
Cry_Jirachi::
Cry_Deoxys::
	.incbin "sound/direct_sound_samples/cries/amongus.bin"

	.align 2
Cry_Chimecho::
	.incbin "sound/direct_sound_samples/cries/amogus.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_88D6978::
	.incbin "sound/direct_sound_samples/88D6978.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_88DBBC0::
	.incbin "sound/direct_sound_samples/88DBBC0.bin"

	.align 2
DirectSoundWaveData_88DC220::
	.incbin "sound/direct_sound_samples/88DC220.bin"

	.align 2
DirectSoundWaveData_88DC704::
	.incbin "sound/direct_sound_samples/88DC704.bin"

	.align 2
DirectSoundWaveData_88DD054::
	.incbin "sound/direct_sound_samples/88DD054.bin"

	.align 2
DirectSoundWaveData_88DDAC4::
	.incbin "sound/direct_sound_samples/88DDAC4.bin"

	.align 2
DirectSoundWaveData_88DDDE4::
	.incbin "sound/direct_sound_samples/88DDDE4.bin"

	.align 2
DirectSoundWaveData_88DEA6C::
	.incbin "sound/direct_sound_samples/88DEA6C.bin"

	.align 2
DirectSoundWaveData_88DF08C::
	.incbin "sound/direct_sound_samples/88DF08C.bin"

	.align 2
DirectSoundWaveData_88DF414::
	.incbin "sound/direct_sound_samples/88DF414.bin"

	.align 2
DirectSoundWaveData_88E01F8::
	.incbin "sound/direct_sound_samples/88E01F8.bin"

	.align 2
DirectSoundWaveData_88E0B68::
	.incbin "sound/direct_sound_samples/88E0B68.bin"

	.align 2
DirectSoundWaveData_88E0F04::
	.incbin "sound/direct_sound_samples/88E0F04.bin"

	.align 2
DirectSoundWaveData_88E16B8::
	.incbin "sound/direct_sound_samples/88E16B8.bin"

	.align 2
DirectSoundWaveData_88E2414::
	.incbin "sound/direct_sound_samples/88E2414.bin"

	.align 2
DirectSoundWaveData_88E2658::
	.incbin "sound/direct_sound_samples/88E2658.bin"

	.align 2
DirectSoundWaveData_88E3498::
	.incbin "sound/direct_sound_samples/88E3498.bin"

	.align 2
DirectSoundWaveData_88E3DEC::
	.incbin "sound/direct_sound_samples/88E3DEC.bin"

	.align 2
DirectSoundWaveData_88E4140::
	.incbin "sound/direct_sound_samples/88E4140.bin"

	.align 2
DirectSoundWaveData_88E4774::
	.incbin "sound/direct_sound_samples/88E4774.bin"

	.align 2
DirectSoundWaveData_88E53E0::
	.incbin "sound/direct_sound_samples/88E53E0.bin"

	.align 2
DirectSoundWaveData_88E5978::
	.incbin "sound/direct_sound_samples/88E5978.bin"

	.align 2
DirectSoundWaveData_88E647C::
	.incbin "sound/direct_sound_samples/88E647C.bin"

	.align 2
DirectSoundWaveData_88E6A80::
	.incbin "sound/direct_sound_samples/88E6A80.bin"

	.align 2
DirectSoundWaveData_88E6C78::
	.incbin "sound/direct_sound_samples/88E6C78.bin"

	.align 2
DirectSoundWaveData_88E75DC::
	.incbin "sound/direct_sound_samples/88E75DC.bin"

	.align 2
DirectSoundWaveData_88E8568::
	.incbin "sound/direct_sound_samples/88E8568.bin"

	.align 2
DirectSoundWaveData_88E8BA0::
	.incbin "sound/direct_sound_samples/88E8BA0.bin"

	.align 2
DirectSoundWaveData_88E9674::
	.incbin "sound/direct_sound_samples/88E9674.bin"

	.align 2
DirectSoundWaveData_88EA5B8::
	.incbin "sound/direct_sound_samples/88EA5B8.bin"

	.align 2
DirectSoundWaveData_88EAB30::
	.incbin "sound/direct_sound_samples/88EAB30.bin"

	.align 2
DirectSoundWaveData_88EB97C::
	.incbin "sound/direct_sound_samples/88EB97C.bin"

	.align 2
DirectSoundWaveData_88EC884::
	.incbin "sound/direct_sound_samples/88EC884.bin"

	.align 2
DirectSoundWaveData_88ED358::
	.incbin "sound/direct_sound_samples/88ED358.bin"

	.align 2
DirectSoundWaveData_88EDEEC::
	.incbin "sound/direct_sound_samples/88EDEEC.bin"

	.align 2
DirectSoundWaveData_88EE8C4::
	.incbin "sound/direct_sound_samples/88EE8C4.bin"

	.align 2
DirectSoundWaveData_88EEF04::
	.incbin "sound/direct_sound_samples/88EEF04.bin"

	.align 2
DirectSoundWaveData_88EF9E4::
	.incbin "sound/direct_sound_samples/88EF9E4.bin"

	.align 2
DirectSoundWaveData_88F0020::
	.incbin "sound/direct_sound_samples/88F0020.bin"

	.align 2
DirectSoundWaveData_88F0738::
	.incbin "sound/direct_sound_samples/88F0738.bin"

	.align 2
DirectSoundWaveData_88F1074::
	.incbin "sound/direct_sound_samples/88F1074.bin"

	.align 2
DirectSoundWaveData_88F1830::
	.incbin "sound/direct_sound_samples/88F1830.bin"

	.align 2
DirectSoundWaveData_88F1D94::
	.incbin "sound/direct_sound_samples/88F1D94.bin"

	.align 2
DirectSoundWaveData_88F2B08::
	.incbin "sound/direct_sound_samples/88F2B08.bin"

	.align 2
DirectSoundWaveData_88F2F84::
	.incbin "sound/direct_sound_samples/88F2F84.bin"

	.align 2
DirectSoundWaveData_88F3470::
	.incbin "sound/direct_sound_samples/88F3470.bin"

	.align 2
DirectSoundWaveData_88F3C38::
	.incbin "sound/direct_sound_samples/88F3C38.bin"

	.align 2
DirectSoundWaveData_88F4834::
	.incbin "sound/direct_sound_samples/88F4834.bin"

	.align 2
DirectSoundWaveData_88F4BAC::
	.incbin "sound/direct_sound_samples/88F4BAC.bin"

	.align 2
DirectSoundWaveData_88F5368::
	.incbin "sound/direct_sound_samples/88F5368.bin"

	.align 2
DirectSoundWaveData_88F5FCC::
	.incbin "sound/direct_sound_samples/88F5FCC.bin"

	.align 2
DirectSoundWaveData_88F6498::
	.incbin "sound/direct_sound_samples/88F6498.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
