	.align 2
voicegroup000:: @ 8675D04
	voice_keysplit_all voicegroup001  @ 8675D04
	voice_keysplit voicegroup005, KeySplitTable1  @ 8675D10
	voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 255, 165, 103, 235  @ 86A724C
	voice_directsound 60, 0, DirectSoundWaveData_trinity_30303_mega_bass, 255, 178, 180, 165  @ 8677B40
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675D34
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 255, 249, 0, 165  @ 86AF7A8
	voice_square_2 60, 0, 2, 0, 0, 9, 2  @ 8675D4C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675D58
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675D64
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 235  @ 8675D70
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0  @ 86ACBB0
	voice_directsound 60, 0, DirectSoundWaveData_heart_of_asia_gamelan, 255, 188, 139, 239  @ 86970E8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675D94
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204  @ 8677BC4
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 165, 90, 216  @ 86ACBE0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675DB8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675DC4
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127  @ 8675DD0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675DDC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675DE8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675DF4
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165  @ 86AF868
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_wind, 255, 0, 255, 127  @ 869D7FC
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, 255, 0, 255, 127  @ 8684F5C
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 128, 204, 103, 226  @ 86ACC58
	voice_directsound 60, 0, DirectSoundWaveData_sc88_26_steel_string_guitar, 255, 252, 0, 239
	voice_directsound 60, 0, DirectSoundWaveData_SMWukulele62, 255, 0, 255, 165  
	voice_directsound 60, 0, DirectSoundWaveData_unused_guitar_separates_power_chord, 255, 165, 206, 127  @ 8676160
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675E54
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 128, 0, 255, 214  @ 86AF8C8
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 128, 0, 255, 206  @ 86AF8D4
	voice_directsound 60, 0, DirectSoundWaveData_sd90_special_scream_drive, 255, 0, 255, 165  @ 86ACCAC
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 149  @ 8675E84
	voice_directsound 60, 0, DirectSoundWaveData_trinity_30303_mega_bass, 255, 0, 255, 127  @ 869D868
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675E9C
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 250, 0, 149  @ 867CCE8
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 115  @ 8675EB4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675EC0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115  @ 8675ECC
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 188  @ 86ACCDC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675EE4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675EF0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675EFC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675F08
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675F14
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165  @ 867919C
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 0, 204  @ 8677360
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 204, 193, 239  @ 8675F38
	voice_keysplit voicegroup006, KeySplitTable2  @ 8675F44
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675F50
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675F5C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675F68
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 255, 0  @ 86B2640
	voice_directsound 60, 0, DirectSoundWaveData_unknown_female_voice, 128, 165, 128, 204  @ 86988D0
	voice_directsound 60, 0, DirectSoundWaveData_unused_unknown_male_voice, 128, 165, 128, 188  @ 86988DC
	voice_directsound 60, 0, DirectSoundWaveData_sc88_55_orchhit60, 255, 0, 255, 165
	voice_keysplit voicegroup007, KeySplitTable3  @ 8675FA4
	voice_directsound 60, 0, DirectSoundWaveData_sc88_55_orchhit72, 255, 0, 255, 165
	voice_keysplit voicegroup008, KeySplitTable4  @ 86773F0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675FC8
	voice_keysplit voicegroup009, KeySplitTable5  @ 8677408
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8675FE0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 0, 255, 209  @ 86AFA54
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFA60
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFA6C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFA78
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFA84
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFA90
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165  @ 86A7114
	voice_directsound 60, 0, DirectSoundWaveData_unused_sd90_oboe, 255, 165, 154, 127  @ 8676154
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFAB4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFAC0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFACC
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127  @ 8677894
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4830, 0, 7, 15, 1  @ 86778A0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_enhanced_delay_shaku, 255, 191, 97, 165  @ 86AC8BC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFAFC
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 0, 255, 204  @ 8695F18
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 255, 0, 255, 127  @ 86ACEE0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFB20
	voice_directsound 60, 0, DirectSoundWaveData_NESPulse1, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_NESPulse2, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_NESPulse3, 255, 0, 255, 165
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sc88pro_jingle_bell, 255, 0, 255, 0  @ 86B075C
	voice_directsound 60, 0, DirectSoundWaveData_sinewavec247, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_triwavec241, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_sqdown60, 255, 0, 255, 165
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFB80
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFB8C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFB98
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 0, 255, 127  @ 869AC64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFBB0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4840, 0, 7, 15, 0  @ 86AFBBC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFBC8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFBD4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFBE0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFBEC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFBF8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFC04
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFC10
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFC1C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFC28
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFC34
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFC40
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFC4C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFC58
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_high, 255, 0, 206, 242  @ 8695BA0
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_low, 255, 0, 206, 242  @ 8696080
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFC7C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFC88
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFC94
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFCA0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFCAC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFCB8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFCC4
	voice_directsound 60, 0, DirectSoundWaveData_SMWsteeldrum52, 255, 0, 255, 165  
	voice_directsound 60, 0, DirectSoundWaveData_SMWbongo71, 255, 0, 255, 165  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFCE8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFCF4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFD00
	voice_directsound 60, 0, DirectSoundWaveData_sd90_special_scream_drive, 255, 0, 255, 165  @ 86AFD0C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFD18
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFD24
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFD30
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFD3C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFD48
	voice_noise_alt 60, 0, 0, 0, 2, 6, 0  @ 86AFD54
	voice_noise_alt 60, 0, 0, 0, 1, 3, 1  @ 86AFD60
	voice_keysplit_all voicegroup177  @ 86AFD6C
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 9, 1  @ 86AFD78
	voice_square_2_alt 60, 0, 2, 0, 2, 9, 1  @ 86AFD84
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4870, 0, 7, 15, 0  @ 86AFD90
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFD9C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFDA8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFDB4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFDC0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFDCC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFDD8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFDE4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFDF0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFDFC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFE08
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFE14
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFE20
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFE2C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFE38
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFE44
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFE50
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFE5C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFE68
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86AFE74
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 0, 255, 127  @ 86ACD0C
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 165, 154, 127  @ 86AFE8C
	voice_keysplit_all voicegroup002  @ 86AFE98
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 3, 1  @ 86AFEA4
	voice_square_2_alt 60, 0, 2, 0, 2, 3, 1  @ 86AFEB0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4870, 0, 7, 15, 0  @ 86AFEBC


