Text_PictureBookShelf: @ 82A81E5
	.string "There's a set of AMOGUS picture books.$"

Text_BookShelf: @ 82A820D
	.string "It's filled with all sorts of books.$"

Text_PokemonCenterBookShelf: @ 82A8232
	.string "AMOGUS magazines!\n"
	.string "AMOGUS PAL…\p"
	.string "AMOGUS HANDBOOK…\n"
	.string "ADORABLE AMOGUS…$"

Text_Vase: @ 82A8276
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan: @ 82A82B3
	.string "It's empty.$"

Text_ShopShelf: @ 82A82BF
	.string "The shelves brim with all sorts of\n"
	.string "AMOGUS merchandise.$"

Text_Blueprint: @ 82A82F7
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
